# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2 
        with:
          python-version: '3.8'
      - name: Install requirements in the first Lambda
        run: | 
          cd lambda_uno
          pip install virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          
      - name: Install requirements in the second Lambda
        run: | 
          cd lambda_2
          pip install virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          
      - name: Check code with Flake8 in the first Lambda
        run: | 
          cd lambda_uno
          source env/bin/activate
          flake8 apps.py
          flake8 test_apps.py
          
      - name: Check code with Flake8 in the second Lambda
        run: | 
          cd lambda_2
          source env/bin/activate
          flake8 apps.py
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN}}
          aws-region: us-east-1
      
      - name: Execution project
        run: | 
          cd lambda_uno
          source env/bin/activate
          zappa update dev
          zappa invoke apps.f
